// ─── Scaffold Publish ──────────────────────────────────────────
// Creates a GitHub repository from scaffold_create's files[] output.
// The "Phase 2" of the underpants gnomes pipeline:
//   scaffold_create → files[] → scaffold_publish → GitHub repo → deploy
//
// Uses GitHub's Git Data API (tree + commit) for atomic multi-file push.

const GITHUB_API = 'https://api.github.com';

interface PublishInput {
  /** Repository name (e.g., "my-restaurant-api") */
  repo_name: string;
  /** GitHub org or user to create the repo under */
  owner: string;
  /** Files to commit */
  files: Array<{ path: string; content: string }>;
  /** Optional: make repo private (default: true) */
  private?: boolean;
  /** Optional: repo description */
  description?: string;
  /** Optional: initial commit message */
  commit_message?: string;
}

interface PublishResult {
  repo_url: string;
  clone_url: string;
  commit_sha: string;
  files_committed: number;
  next_steps: string[];
}

async function ghFetch(
  token: string,
  path: string,
  init?: RequestInit,
): Promise<Response> {
  return fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'User-Agent': 'stackbilt-mcp-gateway',
      'X-GitHub-Api-Version': '2022-11-28',
      ...init?.headers,
    },
    signal: AbortSignal.timeout(30_000),
  });
}

export async function publishToGitHub(
  token: string,
  input: PublishInput,
): Promise<PublishResult> {
  const { repo_name, owner, files, description, commit_message } = input;
  const isPrivate = input.private ?? true;
  const fullRepo = `${owner}/${repo_name}`;

  // 1. Create the repository (auto_init=true ensures Git Data API works)
  const createRes = await ghFetch(token, owner.includes('/') ? '/user/repos' : `/orgs/${owner}/repos`, {
    method: 'POST',
    body: JSON.stringify({
      name: repo_name,
      description: description ?? `Generated by Stackbilt scaffold_create`,
      private: isPrivate,
      auto_init: true, // Required — Git Data API needs at least one commit
    }),
  });

  if (createRes.status === 422) {
    // Repo already exists — that's fine, we'll push to it
    const checkRes = await ghFetch(token, `/repos/${fullRepo}`);
    if (!checkRes.ok) {
      throw new Error(`Repository ${fullRepo} exists but is not accessible`);
    }
  } else if (!createRes.ok) {
    const err = await createRes.text();
    throw new Error(`Failed to create repository: ${err}`);
  } else {
    // New repo — wait briefly for GitHub to process auto_init
    await new Promise(r => setTimeout(r, 1500));
  }

  // 2. Create blobs for each file
  const blobShas: Array<{ path: string; sha: string }> = [];
  for (const file of files) {
    const blobRes = await ghFetch(token, `/repos/${fullRepo}/git/blobs`, {
      method: 'POST',
      body: JSON.stringify({
        content: file.content,
        encoding: 'utf-8',
      }),
    });
    if (!blobRes.ok) {
      const err = await blobRes.text();
      throw new Error(`Failed to create blob for ${file.path}: ${err}`);
    }
    const blob = await blobRes.json() as { sha: string };
    blobShas.push({ path: file.path, sha: blob.sha });
  }

  // 3. Create a tree from all blobs
  const treeRes = await ghFetch(token, `/repos/${fullRepo}/git/trees`, {
    method: 'POST',
    body: JSON.stringify({
      tree: blobShas.map(b => ({
        path: b.path,
        mode: '100644', // regular file
        type: 'blob',
        sha: b.sha,
      })),
    }),
  });
  if (!treeRes.ok) {
    const err = await treeRes.text();
    throw new Error(`Failed to create tree: ${err}`);
  }
  const tree = await treeRes.json() as { sha: string };

  // 4. Get current HEAD to use as parent (from auto_init or existing commits)
  let parentSha: string | undefined;
  try {
    const headRes = await ghFetch(token, `/repos/${fullRepo}/git/ref/heads/main`);
    if (headRes.ok) {
      const ref = await headRes.json() as { object: { sha: string } };
      parentSha = ref.object.sha;
    }
  } catch { /* No HEAD yet — orphan commit */ }

  // Create commit with parent if available
  const commitRes = await ghFetch(token, `/repos/${fullRepo}/git/commits`, {
    method: 'POST',
    body: JSON.stringify({
      message: commit_message ?? `feat: initial scaffold from Stackbilt\n\nGenerated by scaffold_create via Stackbilt MCP gateway.`,
      tree: tree.sha,
      parents: parentSha ? [parentSha] : [],
    }),
  });
  if (!commitRes.ok) {
    const err = await commitRes.text();
    throw new Error(`Failed to create commit: ${err}`);
  }
  const commit = await commitRes.json() as { sha: string };

  // 5. Create/update the main branch ref
  const refRes = await ghFetch(token, `/repos/${fullRepo}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({
      ref: 'refs/heads/main',
      sha: commit.sha,
    }),
  });
  if (!refRes.ok) {
    // Might already exist — try update
    const updateRes = await ghFetch(token, `/repos/${fullRepo}/git/refs/heads/main`, {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha, force: true }),
    });
    if (!updateRes.ok) {
      const err = await updateRes.text();
      throw new Error(`Failed to create/update ref: ${err}`);
    }
  }

  // 6. Set default branch to main
  await ghFetch(token, `/repos/${fullRepo}`, {
    method: 'PATCH',
    body: JSON.stringify({ default_branch: 'main' }),
  }).catch(() => {}); // Non-fatal

  const repoUrl = `https://github.com/${fullRepo}`;
  return {
    repo_url: repoUrl,
    clone_url: `${repoUrl}.git`,
    commit_sha: commit.sha,
    files_committed: files.length,
    next_steps: [
      `git clone ${repoUrl}.git && cd ${repo_name}`,
      `npm install`,
      `npx wrangler d1 create ${repo_name}  # then update database_id in wrangler.toml`,
      `npx wrangler deploy`,
      `# Or connect to Workers Builds for auto-deploy on push`,
    ],
  };
}
