// ─── Scaffold Materializer ─────────────────────────────────────
// Transforms TarotScript scaffold-cast facts into downloadable
// project files. Zero LLM calls — deterministic from facts.
//
// Input:  facts Record from scaffold-cast (~40 key-value pairs)
// Output: files[] array + nextSteps[]
//
// Card-to-file mapping:
//   requirement → .ai/core.adf (product requirements section)
//   interface   → .ai/core.adf (UX section), src/index.ts (route stubs)
//   threat      → .ai/core.adf (security section)
//   runtime     → wrangler.toml, package.json
//   test_plan   → test/index.test.ts
//   first_task  → .ai/state.adf (sprint backlog)
//   aggregates  → .ai/manifest.adf, README.md

export interface ScaffoldFile {
  path: string;
  content: string;
}

export interface MaterializerResult {
  files: ScaffoldFile[];
  nextSteps: string[];
}

type Facts = Record<string, unknown>;

// ─── Helpers ──────────────────────────────────────────────────

function str(facts: Facts, key: string, fallback = ''): string {
  const v = facts[key];
  if (typeof v === 'string') return v;
  if (Array.isArray(v)) return v.join(', ');
  return fallback;
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function traitsInclude(facts: Facts, ...terms: string[]): boolean {
  const v = facts.runtime_traits;
  const joined = Array.isArray(v) ? v.join(' ') : typeof v === 'string' ? v : '';
  return terms.some(t => joined.includes(t));
}

function deriveProjectName(_facts: Facts, intention: string): string {
  // Use first 3-4 meaningful words from intention, skip common prefixes
  const stripped = intention.replace(/^(a|an|the|build|create|make)\s+/i, '');
  return slugify(stripped.split(/\s+/).slice(0, 3).join(' '));
}

// ─── Template Renderers ───────────────────────────────────────

function renderManifestAdf(facts: Facts, projectName: string): string {
  const confidence = str(facts, 'scaffold_confidence', 'moderate');
  const rawBalance = facts.elemental_balance;
  const balance = typeof rawBalance === 'object' && rawBalance !== null
    ? Object.entries(rawBalance as Record<string, number>).filter(([, v]) => v > 0).map(([k, v]) => `${k}:${v}`).join(' ') || 'neutral'
    : str(facts, 'elemental_balance', 'unknown');
  const shadowDensity = facts.shadow_density ?? 'unknown';

  return `# ${projectName} — ADF Manifest
# Generated by scaffold-cast (TarotScript deterministic engine)
# Confidence: ${confidence} | Shadow density: ${shadowDensity}

version: "0.1"
project: "${projectName}"

## Modules

- core.adf        # Product requirements, UX, security
- state.adf       # Sprint backlog and current task

## On-Demand Triggers

| Domain     | Trigger Keywords                     |
|------------|--------------------------------------|
| product    | ${str(facts, 'requirement_name')}, requirements, features |
| ux         | ${str(facts, 'interface_name')}, layout, components |
| security   | ${str(facts, 'threat_name')}, threat, mitigation |
| runtime    | ${str(facts, 'runtime_name')}, deploy, worker |
| testing    | ${str(facts, 'test_plan_name')}, test, coverage |
| sprint     | ${str(facts, 'first_task_name')}, task, estimate |

## Metrics

| Metric              | Value         |
|---------------------|---------------|
| position_count      | ${facts.position_count ?? 6} |
| shadow_density      | ${shadowDensity} |
| elemental_balance   | ${balance}    |
| scaffold_confidence | ${confidence} |
`;
}

function renderCoreAdf(facts: Facts, projectName: string): string {
  const reqName = str(facts, 'requirement_name');
  const reqPriority = str(facts, 'requirement_priority', 'P1');
  const reqEffort = str(facts, 'requirement_effort', 'medium');
  const reqAcceptance = str(facts, 'requirement_acceptance');

  const ifaceName = str(facts, 'interface_name');
  const ifaceRegions = str(facts, 'interface_regions');
  const ifaceGrid = str(facts, 'interface_grid');
  const ifaceComponents = str(facts, 'interface_components');

  const threatName = str(facts, 'threat_name');
  const threatLikelihood = str(facts, 'threat_likelihood');
  const threatImpact = str(facts, 'threat_impact');
  const threatMitigation = str(facts, 'threat_mitigation');

  return `# ${projectName} — Core
# Product requirements, UX patterns, and security constraints

## Product Requirements

### ${reqName}
- **Priority**: ${reqPriority}
- **Effort**: ${reqEffort}
- **Acceptance criteria**: ${reqAcceptance}

## UX Pattern

### ${ifaceName}
- **Regions**: ${ifaceRegions}
- **Grid**: ${ifaceGrid}
- **Components**: ${ifaceComponents}

## Security

### ${threatName}
- **Likelihood**: ${threatLikelihood}
- **Impact**: ${threatImpact}
- **Mitigation**: ${threatMitigation}
`;
}

function renderStateAdf(facts: Facts, projectName: string): string {
  const taskName = str(facts, 'first_task_name');
  const taskEstimate = str(facts, 'first_task_estimate');
  const taskComplexity = str(facts, 'first_task_complexity');
  const taskDeliverable = str(facts, 'first_task_deliverable');

  return `# ${projectName} — State
# Current sprint backlog

## Current Sprint

### ${taskName}
- **Estimate**: ${taskEstimate} points
- **Complexity**: ${taskComplexity}
- **Deliverable**: ${taskDeliverable}
- **Status**: not_started

## Velocity

| Sprint | Points Planned | Points Done |
|--------|---------------|-------------|
| 1      | ${taskEstimate}            | —           |
`;
}

function renderPackageJson(facts: Facts, projectName: string): string {
  const runtimeName = str(facts, 'runtime_name');
  const testFramework = str(facts, 'test_plan_framework', 'vitest');

  // Infer if this is a Workers project from runtime card traits/name
  const isWorkers = traitsInclude(facts, 'edge', 'v8-isolate', 'serverless', 'isolat') ||
    runtimeName.toLowerCase().includes('worker');

  const deps: Record<string, string> = {};
  const devDeps: Record<string, string> = {
    typescript: '^5.5.0',
  };

  if (isWorkers) {
    devDeps['wrangler'] = '^3.0.0';
    devDeps['@cloudflare/workers-types'] = '^4.0.0';
  }

  // Test framework
  if (testFramework.includes('vitest') || testFramework === 'vitest') {
    devDeps['vitest'] = '^2.0.0';
  } else if (testFramework.includes('jest')) {
    devDeps['jest'] = '^29.0.0';
    devDeps['ts-jest'] = '^29.0.0';
  }

  const scripts: Record<string, string> = {
    build: 'tsc',
    typecheck: 'tsc --noEmit',
  };

  if (isWorkers) {
    scripts.dev = 'wrangler dev';
    scripts.deploy = 'wrangler deploy';
  }

  if (testFramework.includes('vitest')) {
    scripts.test = 'vitest run';
  } else {
    scripts.test = 'jest';
  }

  return JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts,
    dependencies: Object.keys(deps).length > 0 ? deps : undefined,
    devDependencies: devDeps,
  }, null, 2);
}

function renderWranglerToml(facts: Facts, projectName: string): string {
  // Infer bindings from runtime card traits
  const bindings: string[] = [];

  if (traitsInclude(facts, 'd1', 'sql', 'database')) {
    bindings.push(`
[[d1_databases]]
binding = "DB"
database_name = "${projectName}"
database_id = "" # TODO: create with wrangler d1 create ${projectName}`);
  }

  if (traitsInclude(facts, 'kv', 'key-value', 'cache')) {
    bindings.push(`
[[kv_namespaces]]
binding = "KV"
id = "" # TODO: create with wrangler kv namespace create ${projectName}`);
  }

  if (traitsInclude(facts, 'queue', 'async', 'background')) {
    bindings.push(`
[[queues.producers]]
queue = "${projectName}-tasks"
binding = "QUEUE"`);
  }

  return `name = "${projectName}"
main = "src/index.ts"
compatibility_date = "${new Date().toISOString().split('T')[0]}"
compatibility_flags = ["nodejs_compat"]
${bindings.join('\n')}
`;
}

function renderIndexTs(facts: Facts): string {
  const ifaceName = str(facts, 'interface_name');
  const reqName = str(facts, 'requirement_name');
  const threatMitigation = str(facts, 'threat_mitigation');

  return `// ${reqName} — main entry point
// UX pattern: ${ifaceName}
// Security: ${threatMitigation || 'standard hardening'}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === '/health') {
      return Response.json({ status: 'ok', timestamp: new Date().toISOString() });
    }

    // TODO: implement ${reqName} handler
    return Response.json({ error: 'not implemented' }, { status: 501 });
  },
} satisfies ExportedHandler<Env>;

interface Env {
  // TODO: add bindings from wrangler.toml
}
`;
}

function renderTestFile(facts: Facts, projectName: string): string {
  const testFramework = str(facts, 'test_plan_framework', 'vitest');
  const coverageTarget = str(facts, 'test_plan_coverage_target', '80%');
  const ciStage = str(facts, 'test_plan_ci_stage', 'pre-merge');
  const reqName = str(facts, 'requirement_name');

  if (testFramework.includes('vitest') || testFramework === 'vitest') {
    return `import { describe, it, expect } from 'vitest';

// Test plan: ${str(facts, 'test_plan_name')}
// CI stage: ${ciStage}
// Coverage target: ${coverageTarget}

describe('${reqName}', () => {
  it('should respond to health check', async () => {
    // TODO: import worker and test with miniflare or unstable_dev
    expect(true).toBe(true);
  });

  it('should handle primary use case', async () => {
    // TODO: implement ${reqName} test
    expect(true).toBe(true);
  });
});
`;
  }

  return `// Test plan: ${str(facts, 'test_plan_name')}
// CI stage: ${ciStage}
// Coverage target: ${coverageTarget}

describe('${reqName}', () => {
  it('should respond to health check', async () => {
    expect(true).toBe(true);
  });
});
`;
}

function renderReadme(facts: Facts, projectName: string, intention: string): string {
  const reqName = str(facts, 'requirement_name');
  const reqPriority = str(facts, 'requirement_priority', 'P1');
  const ifaceName = str(facts, 'interface_name');
  const threatName = str(facts, 'threat_name');
  const runtimeName = str(facts, 'runtime_name');
  const testName = str(facts, 'test_plan_name');
  const taskName = str(facts, 'first_task_name');
  const confidence = str(facts, 'scaffold_confidence', 'moderate');

  return `# ${projectName}

> ${intention}

Scaffolded by [TarotScript](https://github.com/Stackbilt-dev/tarotscript) scaffold-cast. Confidence: **${confidence}**.

## Architecture

| Mode | Card | Key Detail |
|------|------|------------|
| Product | ${reqName} | Priority: ${reqPriority} |
| UX | ${ifaceName} | ${str(facts, 'interface_regions')} |
| Risk | ${threatName} | ${str(facts, 'threat_likelihood')} likelihood, ${str(facts, 'threat_impact')} impact |
| Runtime | ${runtimeName} | ${str(facts, 'runtime_traits')} |
| Test | ${testName} | ${str(facts, 'test_plan_framework')} @ ${str(facts, 'test_plan_ci_stage')} |
| Sprint | ${taskName} | ${str(facts, 'first_task_estimate')} pts, ${str(facts, 'first_task_complexity')} |

## Getting Started

\`\`\`bash
npm install
npx wrangler dev
\`\`\`

## First Task

**${taskName}** — ${str(facts, 'first_task_deliverable')}
- Estimate: ${str(facts, 'first_task_estimate')} points
- Complexity: ${str(facts, 'first_task_complexity')}
`;
}

function renderTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ES2022',
      moduleResolution: 'bundler',
      lib: ['ES2022'],
      types: ['@cloudflare/workers-types'],
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
    },
    include: ['src'],
  }, null, 2);
}

// ─── Main Materializer ───────────────────────────────────────

export function materializeScaffold(
  facts: Facts,
  intention: string,
): MaterializerResult {
  const projectName = deriveProjectName(facts, intention);

  const files: ScaffoldFile[] = [
    // Governance first (.ai/ before src/)
    { path: '.ai/manifest.adf', content: renderManifestAdf(facts, projectName) },
    { path: '.ai/core.adf', content: renderCoreAdf(facts, projectName) },
    { path: '.ai/state.adf', content: renderStateAdf(facts, projectName) },

    // Build config
    { path: 'package.json', content: renderPackageJson(facts, projectName) },
    { path: 'tsconfig.json', content: renderTsConfig() },
    { path: 'wrangler.toml', content: renderWranglerToml(facts, projectName) },

    // Source
    { path: 'src/index.ts', content: renderIndexTs(facts) },

    // Tests
    { path: 'test/index.test.ts', content: renderTestFile(facts, projectName) },

    // Docs
    { path: 'README.md', content: renderReadme(facts, projectName, intention) },
  ];

  const nextSteps = [
    `npm install`,
    `npx wrangler d1 create ${projectName}  # if D1 binding needed`,
    `npx wrangler dev`,
    `# First task: ${str(facts, 'first_task_name')} — ${str(facts, 'first_task_deliverable')}`,
  ];

  return { files, nextSteps };
}
